---
  - name: Check if /var/www/matabit-blog/public exist
    become: true
    file:
      path: /var/www/matabit-blog/public
      state: directory
    
  - name: Unzip pubic.zip 
    become: true
    unarchive:
      src: ~/CIT480/matabit-blog/public.zip
      dest: /var/www/matabit-blog/
  
  - name: Change hugo blog directory to www-data
    become: true
    file:
      path: /var/www/matabit-blog/public
      owner: www-data
      group: www-data

      