---
  - name: Copy get-s3.sh script to /usr/local/bin
    become: true
    template:
      src: get-s3.sh
      dest: /usr/local/bin/get-blog
      mode: +x
  
  - name: Set crontab to get lastest blog version
    become: true
    cron: 
      minute: "5"
      job: "/usr/local/bin/get-blog"

      