---
- name: Run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  roles: 
    - update-cache
    - nginx
    - mkdir-env
    - establish-index-nginx
    - nginx-hugo
    - install-aws-cli
    - configure-datadog
    - ec2-get-blog
    