init_config:
  # Change default path of trusted certificates
  # ca_certs: /etc/ssl/certs/ca-certificates.crt

instances:
  - name: My staging env
    url: https://staging.matabit.org
  
  - name: My prod env
    url: https://matabit.org

    timeout: 1

    # The (optional) http_response_status_code parameter will instruct the check
    # to look for a particular HTTP response status code or a Regex identifying
    # a set of possible status codes.
    # The check will report as DOWN if status code returned differs.
    # This defaults to 1xx, 2xx and 3xx HTTP status code: (1|2|3)\d\d.
    http_response_status_code: (2|3|4|5)\d\d

    # The (optional) collect_response_time parameter will instruct the
    # check to create a metric 'network.http.response_time', tagged with
    # the url, reporting the response time in seconds.
    
    # The latency for requests to the website
    collect_response_time: true

    # The (optional) headers parameter allows you to send extra headers
    # with the request. This is useful for explicitly specifying the host
    # header or perhaps adding headers for authorisation purposes. Note
    # that the http client library converts all headers to lowercase.
    # This is legal according to RFC2616
    # (See: http://tools.ietf.org/html/rfc2616#section-4.2)
    # but may be problematic with some HTTP servers
    # (See: https://code.google.com/p/httplib2/issues/detail?id=169)
    #
    # headers:
    #   Host: alternative.host.example.com
    #   X-Auth-Token: SOME-AUTH-TOKEN

    # The (optional) allow_redirects parameter can enable redirection.
    # Defaults to true.
    #
    # allow_redirects: true

    # The (optional) include_default_headers parameter instructs the check to include the default headers.
    # Default headers can be found at:
    # https://github.com/DataDog/integrations-core/blob/master/datadog_checks_base/datadog_checks/utils/headers.py
    #
    # Defaults to true.
    #
    # include_default_headers: true

    # tags:
    #   - url:http://alternative.host.example.com
    #   - env:production


