init_config:
  # Change default path of trusted certificates
  # ca_certs: /etc/ssl/certs/ca-certificates.crt

instances:
  # Check for nubmer of requests to the website
  - nginx_status_url: http://localhost:81/nginx_status/
