---
- name: make prod and stagingfolder
  become: true
  file:
    path: "/var/www/{{item}}/matabit-blog/public"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
    recurse: yes
  with_items: ["prod", "staging"]
  
  
  

