---
  - name: Install Nginx and Dependencies
    become: true
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - nginx
      
  - name: Change Nginx default site settings
    become: true
    template:
      src: default
      dest: /etc/nginx/sites-available/default
  
  - name: restart nginx
    become: true
    service: 
      name: nginx 
      state: restarted